package com.fnb.membership.fnbmembership.repository.jpa;

import com.fnb.membership.fnbmembership.domain.PointOrder;
import com.fnb.membership.fnbmembership.repository.PointOrderRepository;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * PointOrder Entity JpaRepository
 */
@Repository
public interface PointOrderJpaRepository extends JpaRepository<PointOrder, Long>, PointOrderRepository {

    // Override methods area for PointOrderRepository
    @Override
    <S extends PointOrder> S save(S entity);

    @Override
    Optional<PointOrder> findById(Long id);

    /**
     * This is an adapter interface that performs query method automatically generated by JPA.
     * By using the 'default' keyword, this method is able to call the 'findByMemberIdAndTimeWithPageable' query method
     * @param memberId
     * @param startTime
     * @param endTime
     * @param page
     * @param size
     * @return
     */
    @Override
    default List<PointOrder> findByMemberIdAndTimeOrderByApprovedAtDescWithPaging(Long memberId, LocalDateTime startTime, LocalDateTime endTime, int page, int size) {

        Pageable pageable = PageRequest.of(page, size, Sort.by("approvedAt").descending());
        return findByMemberIdAndTimeWithPageable(memberId, startTime, endTime, pageable);
    }

    // Query Methods area for automatic implementation by JPA
    @Query("SELECT po " +
            "FROM PointOrder po " +
            "WHERE po.memberId = :memberId " +
            "AND po.approvedAt " +
            "BETWEEN :startTime AND :endTime")
    List<PointOrder> findByMemberIdAndTimeWithPageable(Long memberId, LocalDateTime startTime, LocalDateTime endTime, Pageable pageable);
}
